apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: chatbot
spec:
  selector:
    matchLabels:
      app: chatbot
  replicas: 1
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: master
        image: praveengottam/chatbot  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
          protocol: TCP
