apiVersion: v1
kind: Service
metadata:
  name: chatbot
  labels:
    app: chatbot
    deployment: chatbot
spec:
  ports:
  - port: 5000
    name: chatbot
  selector:
    app: chatbot
  type: LoadBalancer
